### ISSUE TITLE
将来的に付与される予定の休暇が申請できない

### ISSUE THREAD

**Issue by yukilabo** [exoego/jobkan-helper#18]
将来的に（翌月等）付与される予定の休暇を事前に申請したいとき、その休暇が選択できない。

こちらの修正によるものだと思います。
https://github.com/exoego/jobkan-helper/commit/a033a8ccea032f30fdea6993eb9159f69fdef712

**Comment by exoego** [comment]
報告ありがとうございます。

現在の挙動は、今月の出勤簿を取得し、そこの休暇残日数をもとにドロップダウンを制御しています。
翌月以降に有給を取得する場合、該当する月の出勤簿を取得すれば「将来付与される休暇」が分かりそうです。

どの月に休暇を取りたいかは「休暇希望日」が変更されたタイミングで把握できそうです。
![image](https://github.com/exoego/jobkan-helper/assets/127635/91a5126b-4c01-4b2f-b903-234aa63dde32)


修正案としてはこんなところを考えました。

1. ❌ この機能を諦める。
    - 自分はこの機能を便利に感じており、「将来付与される休暇を事前に」という状況がほとんどないので、この案はありません
2. 「休暇希望日」が変更されたタイミングで、休暇残日数を計算しなおし、ドロップダウンに反映させる
    - ジョブカンの申請フォームでは「休暇名」が先に来ているので、最初に「休暇名」を選ぼうとした場合は disabled でまごつく→「希望日」を直す→あらためて「休暇名」を選ぶ、という流れになります。
    - この流れは少しびっくりしそうなので「休暇希望日」の横あたりに、「選んだ月に残日数が１以上の休暇名を選べるようになります」などと注意書きを入れるとよさそうです。
3. ドロップダウンのすべてのオプションを enabled にするボタンをつける
    - これが一番手っ取り早いかもしれません

案2が簡単にできそうか試して、面倒そうなら3にします。

**Comment by yukilabo** [comment]
修正案の検討ありがとうございます。
あとは、「残日数が0より多い休暇を上に移動し、残日数0との間に区切り線を入れ、disableにはしない」とかでしょうか。
